package modules

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"database/sql"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"

	"mailcare/app/models"
)

// Master key (settings.secret_key).
//
// One 32-byte key, stored hex-encoded in the settings table of the master
// database, protects two things: the IMAP and SMTP passwords at rest
// (EncryptSecret / DecryptSecret) and the Web session cookies (session.go).
// The key is generated exactly once, on first use, and never regenerated by
// any code path: a read failure or a corrupt stored value aborts the
// operation instead of silently rotating the key, which would make every
// stored password unreadable and every session invalid. Keeping the key in
// the database means a backup of mailcare.db is complete on its own and no
// extra file has to be protected next to it.

const (
	secretKeyLen   = 32 // AES-256
	secretNonceLen = 12 // AES-GCM standard nonce
)

// LoadSecretKey returns the master key, generating and storing it on first
// use. A concurrent first use cannot overwrite another writer's key: the
// insert is conditional on the row being absent and the stored value is
// read back afterwards, so both callers end up with the same key.
func LoadSecretKey(db *sql.DB) ([]byte, error) {
	stored, found, err := models.GetSettingStrict(db, SettingSecretKey)
	if err != nil {
		return nil, fmt.Errorf("failed to read the secret key: %w", err)
	}
	if !found {
		fresh := make([]byte, secretKeyLen)
		if _, err := rand.Read(fresh); err != nil {
			return nil, err
		}
		if err := models.InsertSettingIfAbsent(db, SettingSecretKey, hex.EncodeToString(fresh)); err != nil {
			return nil, fmt.Errorf("failed to store the secret key: %w", err)
		}
		if stored, found, err = models.GetSettingStrict(db, SettingSecretKey); err != nil || !found {
			return nil, fmt.Errorf("failed to read back the secret key: %w", err)
		}
	}
	key, err := hex.DecodeString(stored)
	if err != nil || len(key) != secretKeyLen {
		return nil, errors.New("the stored secret key (settings.secret_key) is corrupt; restore the database from a backup (a new key makes every stored password unreadable)")
	}
	return key, nil
}

func newGCM(key []byte) (cipher.AEAD, error) {
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	return cipher.NewGCM(block)
}

// seal produces nonce || GCM(plaintext).
func seal(gcm cipher.AEAD, plaintext []byte) ([]byte, error) {
	nonce := make([]byte, secretNonceLen)
	if _, err := rand.Read(nonce); err != nil {
		return nil, err
	}
	return gcm.Seal(nonce, nonce, plaintext, nil), nil
}

// open reverses seal.
func open(gcm cipher.AEAD, blob []byte) ([]byte, error) {
	if len(blob) < secretNonceLen {
		return nil, errors.New("ciphertext too short")
	}
	return gcm.Open(nil, blob[:secretNonceLen], blob[secretNonceLen:], nil)
}

// EncryptSecret encrypts a secret (an IMAP password) with the master key and
// returns an opaque base64url string (nonce || AES-256-GCM ciphertext).
func EncryptSecret(key []byte, plaintext string) (string, error) {
	gcm, err := newGCM(key)
	if err != nil {
		return "", err
	}
	blob, err := seal(gcm, []byte(plaintext))
	if err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(blob), nil
}

// DecryptSecret reverses EncryptSecret.
func DecryptSecret(key []byte, encoded string) (string, error) {
	blob, err := base64.RawURLEncoding.DecodeString(encoded)
	if err != nil {
		return "", errors.New("stored secret is not valid base64")
	}
	gcm, err := newGCM(key)
	if err != nil {
		return "", err
	}
	plain, err := open(gcm, blob)
	if err != nil {
		return "", errors.New("stored secret cannot be decrypted with the current key")
	}
	return string(plain), nil
}
