package modules

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
)

// Master key (data/mailcare.key).
//
// One 32-byte key, stored hex-encoded in a 0600 file inside the data
// directory, protects two things: the IMAP passwords at rest in the mailboxes
// table (EncryptSecret / DecryptSecret) and the Web session cookies
// (session.go). The key is generated exactly once, on first use. It is never
// regenerated by any code path: a read failure or a corrupt file aborts the
// operation instead of silently rotating the key, which would make every
// stored password unreadable and every session invalid. An operator who wants
// a new key deletes the file deliberately (and re-enters every IMAP password).

const (
	secretKeyLen   = 32 // AES-256
	secretNonceLen = 12 // AES-GCM standard nonce
)

var (
	secretKeyMu   sync.Mutex
	secretKeyPath string
	secretKey     []byte
)

// SecretKeyPath returns the path of the master key file.
func SecretKeyPath() (string, error) {
	dir, err := DataDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, SecretKeyFileName), nil
}

// LoadSecretKey returns the master key, creating the key file on first use.
// The key is cached per path for the lifetime of the process.
func LoadSecretKey() ([]byte, error) {
	path, err := SecretKeyPath()
	if err != nil {
		return nil, err
	}
	secretKeyMu.Lock()
	defer secretKeyMu.Unlock()
	if secretKey != nil && secretKeyPath == path {
		return secretKey, nil
	}
	key, err := loadOrCreateSecretKey(path)
	if err != nil {
		return nil, err
	}
	secretKey, secretKeyPath = key, path
	return key, nil
}

// loadOrCreateSecretKey reads the key file or creates it atomically when it
// does not exist yet. A concurrent first start cannot overwrite another
// writer's key: creation uses O_EXCL and the loser re-reads the winner's file.
func loadOrCreateSecretKey(path string) ([]byte, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return nil, err
	}
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		fresh := make([]byte, secretKeyLen)
		if _, err := rand.Read(fresh); err != nil {
			return nil, err
		}
		f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
		if err == nil {
			_, werr := f.WriteString(hex.EncodeToString(fresh) + "\n")
			cerr := f.Close()
			if werr != nil {
				return nil, fmt.Errorf("failed to write the secret key file: %w", werr)
			}
			if cerr != nil {
				return nil, fmt.Errorf("failed to write the secret key file: %w", cerr)
			}
			return fresh, nil
		}
		if !errors.Is(err, os.ErrExist) {
			return nil, fmt.Errorf("failed to create the secret key file: %w", err)
		}
		// Somebody else created it in the meantime: use theirs.
		data, err = os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("failed to read the secret key file: %w", err)
		}
	} else if err != nil {
		return nil, fmt.Errorf("failed to read the secret key file: %w", err)
	}
	key, derr := hex.DecodeString(strings.TrimSpace(string(data)))
	if derr != nil || len(key) != secretKeyLen {
		return nil, fmt.Errorf("the secret key file %s is corrupt; restore it from a backup (deleting it makes every stored IMAP password unreadable)", path)
	}
	return key, nil
}

func newGCM(key []byte) (cipher.AEAD, error) {
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	return cipher.NewGCM(block)
}

// seal produces nonce || GCM(plaintext).
func seal(gcm cipher.AEAD, plaintext []byte) ([]byte, error) {
	nonce := make([]byte, secretNonceLen)
	if _, err := rand.Read(nonce); err != nil {
		return nil, err
	}
	return gcm.Seal(nonce, nonce, plaintext, nil), nil
}

// open reverses seal.
func open(gcm cipher.AEAD, blob []byte) ([]byte, error) {
	if len(blob) < secretNonceLen {
		return nil, errors.New("ciphertext too short")
	}
	return gcm.Open(nil, blob[:secretNonceLen], blob[secretNonceLen:], nil)
}

// EncryptSecret encrypts a secret (an IMAP password) with the master key and
// returns an opaque base64url string (nonce || AES-256-GCM ciphertext).
func EncryptSecret(key []byte, plaintext string) (string, error) {
	gcm, err := newGCM(key)
	if err != nil {
		return "", err
	}
	blob, err := seal(gcm, []byte(plaintext))
	if err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(blob), nil
}

// DecryptSecret reverses EncryptSecret.
func DecryptSecret(key []byte, encoded string) (string, error) {
	blob, err := base64.RawURLEncoding.DecodeString(encoded)
	if err != nil {
		return "", errors.New("stored secret is not valid base64")
	}
	gcm, err := newGCM(key)
	if err != nil {
		return "", err
	}
	plain, err := open(gcm, blob)
	if err != nil {
		return "", errors.New("stored secret cannot be decrypted with the current key")
	}
	return string(plain), nil
}
